#!/usr/bin/env bash

## Update the pcodes list.
##
## Usage: fin geojson update-pcodes [-h]
##

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

usage="$(basename "$0") [-h]

where:
    -h  show this help text"

while [ "$1" != "" ]; do
  case $1 in
    -h | --help )         echo "$usage"
                          exit
                          ;;
    * )                   echo "$usage"
                          exit 1
  esac
  shift
done

if [ ! -f "${GEOJSON_ASSET_DIRECTORY}/global_pcodes.csv" ]; then
  curl -s -L https://data.humdata.org/dataset/cb963915-d7d1-4ffa-90dc-31277e24406f/resource/793e66fe-4cdb-4076-b037-fb8c053239e2/download/global_pcodes.csv -o "${GEOJSON_ASSET_DIRECTORY}/global_pcodes.csv"
fi

IFS=,
while read ISO3 ADMIN_LEVEL PCODE
do
  if [[ $ADMIN_LEVEL -gt 3 ]]; then
    continue
  fi

  echo "$ISO3 - $ADMIN_LEVEL"
done < <(tail -n +3 "${GEOJSON_ASSET_DIRECTORY}/global_pcodes.csv" | head)