ghi_content.article_settings:
  type: config_object
  label: 'GHI Article settings'
  mapping:
    subarticle_local_render:
      type: boolean
      label: 'Render sub articles locally'

action.configuration.set_needs_review:
  type: action_configuration_default
  label: 'Set the needs review flag'

action.configuration.unset_needs_review:
  type: action_configuration_default
  label: 'Unset the needs review flag'