ghi_element_sync.settings:
  type: config_object
  label: 'GHI Element sync settings'
  mapping:
    sync_source:
      type: string
      label: 'The sync source url'
    access_key:
      type: string
      label: 'An access key'
    basic_auth:
      type: mapping
      label: 'A basic auth username'
      mapping:
        name:
          type: string
          label: 'A basic auth password'
        pass:
          type: string
          label: 'A basic auth password'
    node_types:
      type: sequence
      label: 'Node types'
      sequence:
        - type: string
          label: 'Node type'
