#!/usr/bin/env bash

## Cleanup the solr core data.
##
## Usage: fin solr cleanup [-h]
##

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"
#   $SOLR_HOST -- (string) the hostname
#   $SOLR_PORT -- (integer) the port
#   $SOLR_CORE -- (string) the core name

usage="$(basename "$0") [-h]

where:
    -h  show this help text"


fin exec --in=solr "solr delete -c $SOLR_CORE -p $SOLR_PORT"
