<?php

/**
 * @file
 * Contains hook implementations for the GHI user module.
 */

/**
 * Implements hook_link_alter().
 *
 * Add the current page url as the destination query argument to the logout
 * link to redirect users back to the current site when logging out. This only
 * works for links added programatically, e.g. for the logout link in the admin
 * toolbar.
 */
function ghi_user_link_alter(&$variables) {
  /** @var \Drupal\Core\Url $url */
  $url = $variables['url'];
  if (!$url->isRouted() || $url->getRouteName() != 'user.logout') {
    return;
  }
  // See if we can provide a destination argument.
  $logout_redirect = ghi_user_get_logout_redirect_service();
  $redirect_url = $logout_redirect->getRedirectUrl();
  if ($redirect_url) {
    $variables['options']['query']['destination'] = $redirect_url->toString();
  }
}

/**
 * Implements hook_preprocess_menu().
 *
 * Add the current page url as the destination query argument to the logout
 * link in the account menu.
 */
function ghi_user_preprocess_menu(&$variables, $hook) {
  if ($hook != 'menu__account' || !array_key_exists('user.logout', $variables['items'])) {
    return;
  }

  // First make sure that this menu is cached taking the destination into
  // consideration.
  $url = $variables['items']['user.logout']['url'];
  $variables['#cache']['contexts'][] = 'url.query_args:destination';
  $current_url = \Drupal::request();
  /** @var \Drupal\Core\Render\RendererInterface $renderer */
  $renderer = \Drupal::service('renderer');
  $renderer->addCacheableDependency($variables, $current_url);

  // Then see if we can provide a destination argument.
  $logout_redirect = ghi_user_get_logout_redirect_service();
  $redirect_url = $logout_redirect->getRedirectUrl();
  if ($redirect_url) {
    /** @var \Drupal\Core\Url $url */
    $query = $url->getOption('query') ?? [];
    $query['destination'] = $redirect_url->toString();
    $url->setOption('query', $query);
  }
}

/**
 * Get the logout redirect service.
 *
 * @return \Drupal\ghi_user\LogoutRedirect
 *   The logout redirect service.
 */
function ghi_user_get_logout_redirect_service() {
  return \Drupal::service('ghi_user.logout_redirect');
}
