<?php

/**
 * @file
 * Contains hook implementations for the GHI teams module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\hpc_common\Helpers\TaxonomyHelper;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_node_access_records().
 */
function ghi_teams_node_access_records(NodeInterface $node) {
  if (!$node->hasField('field_team')) {
    return [];
  }

  $team_id = !$node->field_team->isEmpty() ? $node->field_team->entity->tid->value : NULL;
  $grants = [];
  $grants[] = [
    'realm' => 'ghi_teams_node_access',
    'gid' => 0,
    'grant_view' => $node->isPublished(),
    'grant_update' => 0,
    'grant_delete' => 0,
    'priority' => 0,
  ];

  // Try to get the team from the referenced entity.
  if (!$team_id) {
    $parent_entity = NULL;
    if ($node->hasField('field_entity_reference') && $node->field_entity_reference->entity->hasField('field_team')) {
      $parent_entity = $node->field_entity_reference->entity;
    }

    if (!$team_id && $parent_entity && !$parent_entity->field_team->isEmpty()) {
      $team_id = $parent_entity->field_team->entity->tid->value;
    }
  }

  if (!$team_id) {
    return $grants;
  }
  $grants[] = [
    'realm' => 'ghi_teams_node_access',
    'gid' => $team_id,
    'grant_view' => 1,
    'grant_update' => 1,
    'grant_delete' => 0,
    'priority' => 0,
  ];

  return $grants;
}

/**
 * Implements hook_node_grants().
 */
function ghi_teams_node_grants(AccountInterface $account, $op) {
  $grants = [];
  $grants['ghi_teams_node_access'] = [0];

  $user = User::load($account->id());
  if (!$user->hasField('field_team')) {
    return $grants;
  }

  if ($user->hasPermission('administer teams')) {
    $grants['ghi_teams_node_access'] = array_merge($grants['ghi_teams_node_access'], array_values(array_map(function ($term) {
      return $term->id();
    }, TaxonomyHelper::loadMultipleTermsByVocabulary('team'))));
  }
  elseif (!$user->field_team->isEmpty()) {
    $grants['ghi_teams_node_access'][] = $user->field_team->entity->tid->value;
  }
  return $grants;
}

/**
 * Implements hook_FORM_ID_alter().
 *
 * Restrict access to field_team to users with proper permission.
 */
function ghi_teams_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $user = \Drupal::currentUser();
  $form['field_team']['#access'] = $user->hasPermission('administer teams');
}
