<?php

/**
 * @file
 * Contains hook implementations for the GHI Form Elements module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ghi_form_elements_form_entity_browser_form_alter(array &$form, FormStateInterface $form_state) {
  $form['#attached']['library'][] = 'ghi_form_elements/entity_browser';
}

/**
 * Implements hook_preprocess_html().
 */
function ghi_form_elements_preprocess_html__entity_browser__modal(&$variables) {
  $variables['attributes']['class'][] = 'entity-browser';
  $variables['attributes']['class'][] = 'entity-browser--articles';
}
