<?php

/**
 * @file
 * Contains hook implementations for the GHI Hero Image module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_page().
 *
 * This is used to add the configured hero image (or a default image) to the
 * page title region.
 *
 * This code assumes that there is a page_title region in the theme.
 */
function ghi_hero_image_preprocess_page(&$variables) {
  $region_name = 'page_title';
  if (!array_key_exists($region_name, $variables['page'])) {
    return;
  }

  $request_stack = \Drupal::requestStack();
  $request = $request_stack->getMasterRequest();
  /** @var \Drupal\node\Entity\Node $node */
  $node = $request->attributes->has('node') ? $request->attributes->get('node') : NULL;
  if (!$node instanceof NodeInterface || !$node->getFieldDefinitions() || !$node->access()) {
    return;
  }

  $hero_image_field_definitions = array_filter($node->getFieldDefinitions(), function ($field_definition) {
    return $field_definition->getType() == 'ghi_hero_image';
  });
  if (empty($hero_image_field_definitions)) {
    return;
  }

  // If there are multiple, we only take the first one.
  $hero_image_field_definition = reset($hero_image_field_definitions);

  // We do not check if the field has actual values, because we might want to
  // show a default image.
  $hero_image_field = $node->get($hero_image_field_definition->getName());

  // Get the hero image for the current page.
  $hero_image = $hero_image_field->view();
  if ($hero_image) {
    $hero_image['#label_display'] = 'hidden';
    array_unshift($variables['page'][$region_name], $hero_image);
  }

}
