<?php

namespace Drupal\ghi_blocks\Plugin\Block\Generic;

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Block\Attribute\Block;
use Drupal\Core\Datetime\DateFormatterInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;
use Drupal\ghi_blocks\Interfaces\MultiStepFormBlockInterface;
use Drupal\ghi_blocks\Interfaces\OverrideDefaultTitleBlockInterface;
use Drupal\ghi_blocks\Plugin\Block\GHIBlockBase;
use Drupal\ghi_blocks\ReliefWeb\ReliefWebRssFeed as ReliefWebRssFeedService;
use Drupal\hpc_common\Plugin\HPCBlockMetadata;
use Drupal\link\Plugin\Field\FieldWidget\LinkWidget;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a ReliefWeb RSS feed block.
 */
#[Block(
  id: 'generic_reliefweb_rss_feed',
  admin_label: new TranslatableMarkup('ReliefWeb RSS feed'),
  category: new TranslatableMarkup('Generic elements'),
)]
class ReliefWebRssFeed extends GHIBlockBase implements MultiStepFormBlockInterface, OverrideDefaultTitleBlockInterface {

  private const DEFAULT_ITEM_COUNT = 4;
  private const MIN_ITEM_COUNT = 1;
  private const MAX_ITEM_COUNT = 6;
  private const RENDER_CACHE_MAX_AGE = 3600;

  /**
   * The ReliefWeb RSS feed service.
   *
   * @var \Drupal\ghi_blocks\ReliefWeb\ReliefWebRssFeed
   */
  protected ReliefWebRssFeedService $reliefWebRssFeed;

  /**
   * The date formatter service.
   *
   * @var \Drupal\Core\Datetime\DateFormatterInterface
   */
  protected DateFormatterInterface $dateFormatter;

  /**
   * {@inheritdoc}
   */
  public static function metadata(): ?HPCBlockMetadata {
    return new HPCBlockMetadata(
      defaultTitle: 'Latest situation reports',
      configForms: [
        'feed' => [
          'title' => 'Feed',
          'callback' => 'feedForm',
          'base_form' => TRUE,
        ],
        'display' => [
          'title' => 'Display',
          'callback' => 'displayForm',
        ],
      ]
    );
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    /** @var \Drupal\ghi_blocks\Plugin\Block\Generic\ReliefWebRssFeed $instance */
    $instance = parent::create($container, $configuration, $plugin_id, $plugin_definition);
    $instance->reliefWebRssFeed = $container->get('ghi_blocks.reliefweb_rss_feed');
    $instance->dateFormatter = $container->get('date.formatter');
    return $instance;
  }

  /**
   * {@inheritdoc}
   */
  public function buildContent() {
    $conf = $this->getBlockConfig();
    $feed_url = $conf['feed']['feed_url'] ?? NULL;
    if (empty($feed_url)) {
      return NULL;
    }

    $item_count = $this->sanitizeItemCount($conf['display']['item_count'] ?? self::DEFAULT_ITEM_COUNT);
    $items = $this->reliefWebRssFeed->getItems($feed_url, $item_count);
    if (empty($items)) {
      return NULL;
    }

    return [
      '#theme' => 'reliefweb_rss_feed',
      '#items' => array_map(fn (array $item) => $this->buildItem($item), $items),
      '#view_more_link' => $this->buildViewMoreLink($conf['display'] ?? []),
      '#cache' => [
        'max-age' => self::RENDER_CACHE_MAX_AGE,
        'tags' => [
          $this->reliefWebRssFeed->getCacheTag($feed_url),
        ],
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  protected function getConfigurationDefaults() {
    return [
      'feed' => [
        'feed_url' => NULL,
      ],
      'display' => [
        'item_count' => self::DEFAULT_ITEM_COUNT,
        'view_more_url' => NULL,
        'view_more_label' => NULL,
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getDefaultSubform($is_new = FALSE) {
    return 'feed';
  }

  /**
   * {@inheritdoc}
   */
  public function getTitleSubform() {
    return 'display';
  }

  /**
   * {@inheritdoc}
   */
  public function isEmpty(): bool {
    $conf = $this->getBlockConfig();
    return empty($conf['feed']['feed_url']);
  }

  /**
   * {@inheritdoc}
   */
  protected function hasReliableIsEmpty(): bool {
    return TRUE;
  }

  /**
   * Build the feed configuration form.
   */
  public function feedForm(array $form, FormStateInterface $form_state) {
    $form['feed_url'] = [
      '#type' => 'textfield',
      '#title' => $this->t('ReliefWeb RSS feed URL'),
      '#description' => $this->t('Paste the full RSS feed URL generated by ReliefWeb filters, for example https://reliefweb.int/country/ven/rss.xml?format=10.'),
      '#default_value' => $this->getDefaultFormValueFromFormState($form_state, 'feed_url'),
      '#required' => TRUE,
      '#required_error' => $this->t('Please enter a full ReliefWeb RSS URL, for example https://reliefweb.int/country/ven/rss.xml?format=10.'),
      '#maxlength' => 2048,
    ];

    return $form;
  }

  /**
   * Build the display configuration form.
   */
  public function displayForm(array $form, FormStateInterface $form_state) {
    $options = array_combine(range(self::MIN_ITEM_COUNT, self::MAX_ITEM_COUNT), range(self::MIN_ITEM_COUNT, self::MAX_ITEM_COUNT));

    $form['item_count'] = [
      '#type' => 'select',
      '#title' => $this->t('Number of items'),
      '#options' => $options,
      '#default_value' => $this->sanitizeItemCount($this->getDefaultFormValueFromFormState($form_state, 'item_count') ?? self::DEFAULT_ITEM_COUNT),
      '#required' => TRUE,
    ];

    $form['view_more_url'] = [
      '#type' => 'textfield',
      '#title' => $this->t('View more URL'),
      '#description' => $this->t('Add an optional link to the full ReliefWeb result list.'),
      '#default_value' => $this->getDefaultFormValueFromFormState($form_state, 'view_more_url'),
      '#maxlength' => 2048,
      '#element_validate' => [
        [LinkWidget::class, 'validateUriElement'],
      ],
    ];

    $form['view_more_label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('View more label'),
      '#description' => $this->t('Leave empty to use the default label.'),
      '#default_value' => $this->getDefaultFormValueFromFormState($form_state, 'view_more_label'),
      '#maxlength' => 255,
      '#placeholder' => $this->t('View more on ReliefWeb'),
    ];

    return $form;
  }

  /**
   * Validate handler for the block configuration form.
   */
  public function blockValidate($form, FormStateInterface $form_state) {
    $current_subform = $form_state->get('current_subform');
    $values = $form_state->getValue($current_subform) ?? [];
    $subform = $form['container'] ?? [];
    $triggering_element = $form_state->getTriggeringElement();
    $is_final_submit = ($triggering_element['#parents'] ?? NULL) === ['actions', 'submit'];

    if ($current_subform === 'feed' && (array_key_exists('feed_url', $subform) || $is_final_submit)) {
      $feed_url = trim($values['feed_url'] ?? $this->getDefaultFormValueFromFormState($form_state, 'feed_url') ?? '');
      if (!$this->reliefWebRssFeed->isValidFeedUrl($feed_url)) {
        $message = $this->t('Please enter a full ReliefWeb RSS URL, for example https://reliefweb.int/country/ven/rss.xml?format=10.');
        if (array_key_exists('feed_url', $subform)) {
          $form_state->setError($subform['feed_url'], $message);
        }
        else {
          $form_state->set('preview', FALSE);
          $form_state->setErrorByName('feed][feed_url', $message);
        }
      }
    }

    if ($current_subform === 'display' && array_key_exists('item_count', $subform)) {
      $item_count = (int) ($values['item_count'] ?? self::DEFAULT_ITEM_COUNT);
      if ($item_count < self::MIN_ITEM_COUNT || $item_count > self::MAX_ITEM_COUNT) {
        $form_state->setError($subform['item_count'], $this->t('Please choose between @min and @max items.', [
          '@min' => self::MIN_ITEM_COUNT,
          '@max' => self::MAX_ITEM_COUNT,
        ]));
      }

      $view_more_url = trim($values['view_more_url'] ?? '');
      if ($view_more_url && !UrlHelper::isValid($view_more_url, TRUE)) {
        $form_state->setError($subform['view_more_url'], $this->t('Please enter a full URL, including the protocol.'));
      }
    }
  }

  /**
   * Build a single rendered item.
   *
   * @param array $item
   *   A parsed ReliefWeb RSS feed item.
   *
   * @return array
   *   The template item.
   */
  private function buildItem(array $item): array {
    $title = $item['title'] ?? '';
    $url = $item['url'] ?? '';
    $timestamp = $item['timestamp'] ?? NULL;

    $link = Link::fromTextAndUrl($title, Url::fromUri($url));
    $link->getUrl()->setOptions([
      'attributes' => [
        'class' => ['reliefweb-rss-feed__item-link'],
        'target' => '_blank',
        'rel' => 'noopener',
      ],
    ]);

    return [
      'title' => $title,
      'link' => $link->toRenderable(),
      'formatted_date' => $timestamp ? $this->dateFormatter->format($timestamp, 'custom', 'j M Y') : NULL,
      'source' => $item['source'] ?? '',
    ];
  }

  /**
   * Build the optional "View more" link.
   *
   * @param array $display_config
   *   The display configuration.
   *
   * @return array|null
   *   The link render array, or NULL when no URL is configured.
   */
  private function buildViewMoreLink(array $display_config): ?array {
    if (empty($display_config['view_more_url']) || !UrlHelper::isValid($display_config['view_more_url'], TRUE)) {
      return NULL;
    }

    $label = trim($display_config['view_more_label'] ?? '') ?: $this->t('View more on ReliefWeb');
    $link = Link::fromTextAndUrl($label, Url::fromUri($display_config['view_more_url']));
    $link->getUrl()->setOptions([
      'attributes' => [
        'class' => ['cd-button', 'external', 'reliefweb-rss-feed__view-more-link'],
        'target' => '_blank',
        'rel' => 'noopener',
      ],
    ]);
    return $link->toRenderable();
  }

  /**
   * Normalize the configured item count.
   *
   * @param mixed $item_count
   *   The configured value.
   *
   * @return int
   *   The safe item count.
   */
  private function sanitizeItemCount(mixed $item_count): int {
    return min(self::MAX_ITEM_COUNT, max(self::MIN_ITEM_COUNT, (int) $item_count));
  }

}
