<?php

/**
 * @file
 * Contains requirement checks for the GHI Content module.
 */

/**
 * Implements hook_requirements().
 */
function ghi_content_requirements($phase) {
  $requirements = [];
  if ($phase == 'runtime') {
    $remote_sources = \Drupal::config('ghi_content.remote_sources')->get();
    foreach ($remote_sources as $key => $config) {
      /** @var \Drupal\ghi_content\RemoteSource\RemoteSourceInterface $remote_source */
      $remote_source = \Drupal::service('plugin.manager.remote_source')->createInstance($key);
      $connection_status = $remote_source->checkConnection();
      $string_args = [
        '@url' => $remote_source->getRemoteEndpointUrl(),
      ];
      $requirements['ghi_content_remote_source_' . $key] = [
        'title' => $remote_source->getPluginLabel(),
        'severity' => $connection_status ? REQUIREMENT_OK : REQUIREMENT_ERROR,
        // 'value' => $connection_status ? t('Success') : t('Failed'),
        'value' => $connection_status ? t('Connection to the remote source at <em>@url</em> successful.', $string_args) : t('Connection to the remote source at <em>@url</em> failed.', $string_args),
      ];
      $article_ids = $remote_source->getImportIds('article');
      $article_id = array_shift($article_ids);
      $article = $remote_source->getArticle($article_id, FALSE);
      $requirements['ghi_content_remote_source_' . $key . '_article'] = [
        'title' => $remote_source->getPluginLabel() . ': Articles',
        'severity' => $article ? REQUIREMENT_OK : REQUIREMENT_ERROR,
        // 'value' => $article ? t('Success') : t('Failed'),
        'value' => $article ? t('Article data can be retrieved.') : t('Article data cannot be retrieved.'),
      ];

      $document_ids = $remote_source->getImportIds('document');
      $document_id = array_shift($document_ids);
      $document = $remote_source->getDocument($document_id, FALSE);
      $requirements['ghi_content_remote_source_' . $key . '_document'] = [
        'title' => $remote_source->getPluginLabel() . ': Documents',
        'severity' => $document ? REQUIREMENT_OK : REQUIREMENT_ERROR,
        // 'value' => $document ? t('Success') : t('Failed'),
        'value' => $document ? t('Document data can be retrieved.') : t('Document data cannot be retrieved.'),
      ];
    }
  }
  return $requirements;
}

/**
 * Implements hook_update_last_removed().
 */
function ghi_content_update_last_removed(): int {
  return 9006;
}
