<?php

/**
 * @file
 * Global functions for the HPC API module.
 */

use Drupal\Core\File\FileSystemInterface;
use Drupal\hpc_api\Helpers\QueryHelper;

/**
 * Implements hook_cache_flush().
 *
 * Clean up import files.
 */
function hpc_api_cache_flush() {
  hpc_api_clear_directory_contents(QueryHelper::IMPORT_DIR);
}

/**
 * Delete and recreate the given directory.
 *
 * Use this only for directories whose whole contents are disposable.
 *
 * @param string $dir
 *   The directory to clear.
 */
function hpc_api_clear_directory_contents($dir) {
  /** @var \Drupal\Core\File\FileSystem $file_system */
  $file_system = \Drupal::service('file_system');
  if (file_exists($dir)) {
    $file_system->deleteRecursive($dir);
  }
  $file_system->prepareDirectory($dir, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);
}

/**
 * Delete files in the given directory.
 *
 * @param string $dir
 *   The directory to clear.
 */
function hpc_api_clear_directory($dir, $pattern) {
  /** @var \Drupal\Core\File\FileSystem $file_system */
  $file_system = \Drupal::service('file_system');
  $import_files = file_exists($dir) ? $file_system->scanDirectory($dir, $pattern) : [];
  if (empty($import_files)) {
    // Nothing to be done.
    return;
  }
  foreach ($import_files as $import_file) {
    $file_system->delete($import_file->uri);
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 *
 * Make sure that all routes under the hpc_api.reports.files routing namespace
 * show the purge link.
 */
function hpc_api_menu_local_actions_alter(&$local_actions) {
  $routes = \Drupal::service('router.route_provider')->getAllRoutes();
  $route_names = array_filter(array_keys((array) $routes), function ($route_name) {
    return str_starts_with($route_name, 'hpc_api.reports.files');
  });
  $local_actions['hpc_api.purge_files']['appears_on'] = array_values($route_names);
}
