<?php

/**
 * @file
 * Hook implementations for GHI Menu.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Session\AccountInterface;
use Drupal\ghi_menu\Entity\GhiMenuLinkContent;
use Drupal\ghi_menu\Form\MenuLinkDeleteWithSublinksForm;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\VocabularyInterface;

/**
 * Implements hook_menu_local_actions_alter().
 */
function ghi_menu_menu_local_actions_alter(&$local_actions) {
  $local_actions['node.add_page']['class'] = 'Drupal\ghi_menu\LocalAction\LocalActionContent';
}

/**
 * Implements hook_entity_type_build().
 */
function ghi_menu_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\ContentEntityTypeInterface $entity_type */
  $entity_type = $entity_types['menu_link_content'];
  $entity_type
    ->setClass(GhiMenuLinkContent::class)
    ->setFormClass('delete', MenuLinkDeleteWithSublinksForm::class);
}

/**
 * Implements hook_entity_operation().
 */
function ghi_menu_entity_operation(EntityInterface $entity) {
  if (!$entity instanceof NodeInterface) {
    return;
  }
  /** @var \Drupal\ghi_menu\GhiEntityOperationsManager $operations_manager */
  $operations_manager = \Drupal::service('ghi_menu.entity_operations_manager');
  return $operations_manager->getOperationLinks($entity);
}

/**
 * Implements hook_entity_operation_alter().
 */
function ghi_menu_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    unset($operations['translate']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ghi_menu_form_taxonomy_overview_vocabularies_alter(&$form, FormStateInterface $form_state) {
  $current_user = \Drupal::currentUser();
  foreach (Element::children($form['vocabularies']) as $vid) {
    $vocabulary = \Drupal::entityTypeManager()->getStorage('taxonomy_vocabulary')->load($vid);
    if (!$current_user->hasPermission('edit terms in ' . $vocabulary->id())) {
      unset($form['vocabularies'][$vid]);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function ghi_menu_taxonomy_vocabulary_access(VocabularyInterface $vocabulary, $operation, AccountInterface $account) {
  if (!$account->hasPermission('edit terms in ' . $vocabulary->id())) {
    return AccessResult::forbidden();
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_preprocess_breadcrumb().
 */
function ghi_menu_preprocess_breadcrumb(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    $variables['gin_breadcrumb_skip'] = TRUE;
  }
}
