<?php

/**
 * @file
 * Contains hook implementations for the GHI Custom Subpages module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\ghi_subpages_custom\CustomSubpageManager;
use Drupal\ghi_sections\Entity\GlobalSection;
use Drupal\ghi_subpages_custom\Entity\CustomSubpage;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ghi_subpages_custom_entity_bundle_info_alter(array &$bundles) {
  $bundles['node']['custom_subpage']['class'] = CustomSubpage::class;
  $bundles['node']['custom_subpage']['label'] = t('Custom subpage');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ghi_subpages_custom_form_node_custom_subpage_edit_form_alter(&$form, FormStateInterface &$form_state) {

  // Restrict access to the team field.
  if (!\Drupal::currentUser()->hasPermission('administer teams')) {
    $form['field_team']['#disabled'] = TRUE;
    $form['field_team']['widget']['#description'] = t('You do not have permission to change the team for this section.');
  }
}

/**
 * Implements hook_subpage_navigation_links().
 */
function ghi_subpages_custom_subpage_navigation_links_alter(&$links, array $context, array &$cache_tags) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $context['node'];

  /** @var \Drupal\node\NodeInterface $base_entity */
  $base_entity = $context['base_entity'];

  if ($node->bundle() == CustomSubpageManager::BUNDLE && $base_entity instanceof GlobalSection) {
    // Custom subpages of global sections, shouldn't have any navigation
    // links for the moment.
    $links = [];
  }

  // Load custom subpage for the base entity.
  /** @var \Drupal\ghi_subpages_custom\CustomSubpageManager $custom_subpage_manager */
  $custom_subpage_manager = \Drupal::service('ghi_subpages_custom.manager');

  $custom_subpages = $custom_subpage_manager->loadNodesForSection($base_entity);
  if (empty($custom_subpages)) {
    return;
  }

  foreach ($custom_subpages as $subpage) {
    // We merge the cache tags even if the custom subpage node is not
    // available, as that might change.
    $cache_tags = Cache::mergeTags($cache_tags, $subpage->getCacheTags());

    // Check if the page should be visible.
    if (!$subpage->access('view')) {
      continue;
    }
    $link = $subpage->toLink(NULL, 'canonical', ['fragment' => 'page-title'])->toRenderable();
    if ($node->id() == $subpage->id() && ($subpage->access('view') || $subpage->access('update'))) {
      $link['#attributes']['class'][] = 'active';
      if (!$subpage->isPublished()) {
        $link['#attributes']['class'][] = 'node--unpublished';
      }
      // Get the subheadings and add quick links on the current page.
      $subheadings = $custom_subpage_manager->getSubHeadings($subpage);
      if (!empty($subheadings)) {
        $link['children'] = [];
        foreach ($subheadings as $id => $subheading) {
          $link['children'][] = Link::fromTextAndUrl($subheading, Url::fromUserInput('#' . $id))->toString();
        }
      }
    }
    $links[] = $link;
  }
}

/**
 * Implements hook_is_subpage_type().
 */
function ghi_subpages_custom_is_subpage_type($node_type) {
  return in_array($node_type, [CustomSubpageManager::BUNDLE]);
}
