<?php

/**
 * @file
 * Contains hook implementations for the GHI Custom Subpages module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\ghi_sections\Entity\Section;
use Drupal\ghi_subpages_custom\CustomSubpageManager;
use Drupal\ghi_subpages_custom\Entity\CustomSubpage;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ghi_subpages_custom_entity_bundle_info_alter(array &$bundles) {
  $bundles['node']['custom_subpage']['class'] = CustomSubpage::class;
  $bundles['node']['custom_subpage']['label'] = t('Custom subpage');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ghi_subpages_custom_form_node_custom_subpage_edit_form_alter(&$form, FormStateInterface &$form_state) {
  // Restrict access to the team field.
  if (!\Drupal::currentUser()->hasPermission('administer teams')) {
    $form['field_team']['#disabled'] = TRUE;
    $form['field_team']['widget']['#description'] = t('You do not have permission to change the team for this section.');
  }
}

/**
 * Implements hook_section_subpage_nodes().
 */
function ghi_subpages_custom_section_subpage_nodes(Section $section) {
  /** @var \Drupal\ghi_subpages_custom\CustomSubpageManager $custom_subpage_manager */
  $custom_subpage_manager = \Drupal::service('ghi_subpages_custom.manager');
  return $custom_subpage_manager->loadNodesForSection($section) ?? [];
}

/**
 * Implements hook_is_subpage_type().
 */
function ghi_subpages_custom_is_subpage_type($node_type) {
  return in_array($node_type, [CustomSubpageManager::BUNDLE]);
}
