<?php

/**
 * @file
 * Contains hook implementations for the GHI documents module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ghi_documents_form_node_document_edit_form_alter(&$form, FormStateInterface &$form_state) {

  // Restrict access to the team field.
  if (!\Drupal::currentUser()->hasPermission('administer teams')) {
    $form['field_team']['#disabled'] = TRUE;
    $form['field_team']['widget']['#description'] = t('You do not have permission to change the team for this section.');
  }
}

/**
 * Implements hook_subpage_navigation_links().
 */
function ghi_documents_subpage_navigation_links_alter(&$links, array $context) {
  /** @var \Drupal\node\NodeInterface $base_entity */
  $base_entity = $context['base_entity'];

  // Load documents for the base entity.
  /** @var \Drupal\ghi_documents\DocumentManager $document_manager */
  $document_manager = \Drupal::service('ghi_documents.manager');

  $documents = $document_manager->loadNodesForSection($base_entity);
  if (empty($documents)) {
    return;
  }
  foreach ($documents as $document) {
    $links[] = $document->toLink(NULL)->toRenderable();
  }
}

/**
 * Implements hook_is_subpage_type().
 */
function ghi_documents_is_subpage_type($node_type) {
  return in_array($node_type, ['document']);
}
