version: "2.1"

services:
  cli:
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - MAPBOX_TOKEN
  web:
    environment:
      - MAPBOX_TOKEN
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug:3.141.59
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900

  snap:
    image: public.ecr.aws/unocha/tools-snap-service:v3.0.4
    mem_limit: 4g
    cpu_quota: 200000
    shm_size: 1G
    ports:
      - "8444:8442"
    environment:
      - ALLOWED_HOSTNAMES=docksal.site