version: "3.9"

services:
  cli:
    volumes:
      - ${PROJECT_ROOT}/html/sites/simpletest/:/var/www/html/sites/simpletest:rw
    environment:
      - HPC_API_USER
      - HPC_API_PASS
      - HPC_API_KEY
      - HID_CLIENT_ID
      - HID_CLIENT_SECRET
      - CM_KEY
      - MAPBOX_TOKEN
      - COMPOSER_MEMORY_LIMIT=-1
      - SOLR_CORE
      - SOLR_HOST
      - SOLR_PORT

  web:
    environment:
      - MAPBOX_TOKEN

  browser:
    hostname: browser
    # image: seleniarm/standalone-chromium:latest
    image: seleniarm/standalone-chromium:103.0
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /tmp:/dev/shm
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    ports:
      - 5903:5903

  snap:
    image: public.ecr.aws/unocha/tools-snap-service:v3.0.4
    mem_limit: 4g
    cpu_quota: 200000
    shm_size: 1G
    ports:
      - "8444:8442"
    environment:
      - ALLOWED_HOSTNAMES=docksal.site

  # Solr
  solr:
    image: arm64v8/solr:8
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/solr811:/opt/solr/server/solr/configsets/solr811
    environment:
      SOLR_CORE: ${SOLR_CORE:-ghi}

  memcached:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: memcached