services:
  cli:
    volumes:
      - ${PROJECT_ROOT}/html/sites/simpletest/:/var/www/html/sites/simpletest:rw
    environment:
      - HPC_API_USER
      - HPC_API_PASS
      - HPC_API_KEY
      - HID_CLIENT_ID
      - HID_CLIENT_SECRET
      - CM_KEY
      - MAPBOX_TOKEN
      - COMPOSER_MEMORY_LIMIT=-1
      - SOLR_CORE
      - SOLR_HOST
      - SOLR_PORT
      - 'SNAP_URL=${VIRTUAL_HOST}:8444/snap'
      - XDEBUG_ENABLED=1
      - XDEBUG_MODE=off

  web:
    environment:
      - MAPBOX_TOKEN

  browser:
    hostname: browser
    image: selenium/standalone-chromium:latest
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /tmp:/dev/shm
      - ${PROJECT_ROOT}/logs/chromedriver:/var/log/chromedriver
    environment:
      # - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - 'JAVA_OPTS=-Dwebdriver.chrome.logfile=/var/log/chromedriver/chromedriver.log'
      - 'SE_NODE_MAX_SESSIONS=2'
      - 'SE_NODE_STEREOTYPE={"browserName": "chrome"}'
      - 'SE_VNC_NO_PASSWORD=1'
    # shm_size: '2gb'
    ports:
      - 5900:5900
      - 7900:7900
      - 4444:4444

  snap:
    image: public.ecr.aws/unocha/tools-snap-service:dev-chromium
    mem_limit: 4g
    cpu_quota: 200000
    shm_size: 1G
    ports:
      - "8444:8442"
    environment:
      - ALLOWED_HOSTNAMES=docksal.site

  # Solr
  solr:
    image: arm64v8/solr:8
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/solr811:/opt/solr/server/solr/configsets/solr811
    environment:
      SOLR_CORE: ${SOLR_CORE:-ghi}

  memcached:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: memcached