display:
  default:
    display_title: Maître
    display_options:
      title: Journal
      fields:
        sensor_status:
          label: Status
        sensor_message:
          label: "Message d'état"
        timestamp:
          label: Horodatage
      pager:
        options:
          tags:
            next: "suivant\_›"
            previous: "‹\_précédent"
            first: "«\_premier"
            last: "dernier\_»"
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      arguments:
        sensor_name:
          exception:
            title: Tout
  detail_page_log:
    display_options:
      fields:
        timestamp:
          label: Horodatage
        sensor_status:
          label: Status
        sensor_message:
          label: "Message d'état"
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Journal
