label: Content
description: 'Find and manage content.'
display:
  default:
    display_title: Maître
    display_options:
      title: Content
      fields:
        title:
          label: Title
        type:
          label: 'Content type'
        name:
          label: Author
        status:
          label: Status
          settings:
            format_custom_false: Unpublished
            format_custom_true: Published
        changed:
          label: Updated
        operations:
          label: Actions
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      empty:
        area_text_custom:
          content: 'No content available.'
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
