label: Média
description: 'Trouver et gérer des media.'
display:
  default:
    display_title: Maître
    display_options:
      title: Média
      fields:
        media_bulk_form:
          action_title: Action
        thumbnail__target_id:
          label: Vignette
          separator: ', '
        name:
          label: 'Nom du média'
          separator: ', '
        bundle:
          label: Type
          separator: ', '
        uid:
          label: Author
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_false: 'Non publié'
            format_custom_true: Displayed
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: Actions
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'Aucun média disponible.'
      filters:
        name:
          expose:
            label: 'Nom du média'
        bundle:
          expose:
            label: Type
        status:
          expose:
            label: Vrai
          group_info:
            label: 'Display status'
            group_items:
              1:
                title: Displayed
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: Language
  media_page_list:
    display_title: Média
    display_options:
      menu:
        title: Média
