<?php

/**
 * @file
 * Contains hook implementations for the GHI Plans module.
 */

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\ghi_base_objects\Helpers\BaseObjectHelper;
use Drupal\hpc_common\Helpers\CommonHelper;

/**
 * Implements hook_page_attachments().
 */
function ghi_plans_page_attachments(array &$page) {
  $cache = CacheableMetadata::createFromRenderArray($page);
  $page['#attached']['html_head_link'][] = [
    [
      'href' => 'https://fonts.googleapis.com/icon?family=Material+Icons',
      'rel' => 'stylesheet',
    ],
  ];
  // Apply updated caching information.
  $cache->applyTo($page);
}

/**
 * Implements hook_preprocess_page().
 */
function ghi_plans_preprocess_page(array &$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'] ?? NULL;
  /** @var \Drupal\ghi_base_objects\Entity\BaseObjectInterface $base_object */
  $base_object = $node ? BaseObjectHelper::getBaseObjectFromNode($node) : NULL;
  if ($base_object && $base_object->bundle() == 'plan') {
    $decimal_format = $base_object->get('field_decimal_format')->value;
    $variables['#attached']['drupalSettings']['plan_settings'] = [
      'decimal_format' => $decimal_format,
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function ghi_plans_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if (CommonHelper::isAjaxRequest()) {
    return;
  }
  $valid_form_ids = [
    'base_object_plan_edit_form',
    // 'node_plan_entity_edit_form',
    // 'node_governing_entity_edit_form',
  ];
  if (!in_array($form_id, $valid_form_ids)) {
    return;
  }

  // Disable all form elements except the listed ones.
  $allow_editing = [
    'form_id',
    'form_build_id',
    'form_token',
    'field_content',
    'status',
  ];
  foreach (Element::children($form) as $element_key) {
    if (in_array($element_key, $allow_editing)) {
      continue;
    }
    $form[$element_key]['#disabled'] = 'disabled';
  }
  \Drupal::messenger()->addWarning(t('Most of the data in this form is imported automatically from the HPC API and cannot be changed here.'));
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Selectively allow specific fields on edit pages of plan base objects.
 */
function ghi_plans_form_base_object_plan_edit_form_alter(&$form, FormStateInterface &$form_state) {
  $allow_fields = [
    'field_decimal_format',
    'field_plan_caseload',
    'field_plan_document_link',
    'field_plan_status_string',
    'field_short_name',
    'field_footnotes',
  ];
  foreach (Element::children($form) as $element_key) {
    if (!in_array($element_key, $allow_fields) && $form[$element_key]['#type'] != 'actions') {
      continue;
    }
    unset($form[$element_key]['#disabled']);
  }
}
