_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - '// Smugmug API'
  - 'smugmug_api.settings:api_key'
  - 'smugmug_api.settings:api_secret'
  - '// Ignore global settings.'
  - ghi_blocks.global_settings
  - '// Ignore connection credentials.'
  - ghi_content.remote_sources
  - '// Ignore the image settings'
  - ghi_hero_image.config
  - '// Ignore the homepage config.'
  - 'page_manager.page.homepage:access_logic'
  - 'page_manager.page.homepage:access_conditions'
  - 'page_manager.page_variant.homepage*:variant_settings.sections.0.components'
  - '// Ignore cache warmer'
  - warmer.settings
  - '// Protected password'
  - 'protected_pages.settings:password.protected_pages_global_password'
enable_export_filtering: true
