_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: simple
ignored_config_entities:
  - 'entity_access_password.settings:global_password'
  - ghi_blocks.global_settings
  - ghi_content.article_settings
  - ghi_content.remote_sources
  - ghi_embargoed_access.settings
  - ghi_hero_image.config
  - 'page_manager.page.homepage:access_conditions'
  - 'page_manager.page.homepage:access_logic'
  - 'page_manager.page_variant.homepage*:variant_settings.sections.0.components'
  - 'smugmug_api.settings:api_key'
  - 'smugmug_api.settings:api_secret'
  - warmer.settings
enable_export_filtering: true
