_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cer: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fpa: 0
  ghi_base_objects: 0
  ghi_blocks: 0
  ghi_content: 0
  ghi_element_sync: 0
  ghi_form_elements: 0
  ghi_hero_image: 0
  ghi_plans: 0
  ghi_sections: 0
  ghi_subpages: 0
  ghi_teams: 0
  gho_footnotes: 0
  gin_lb: 0
  gin_toolbar: 0
  hpc_api: 0
  hpc_common: 0
  hpc_downloads: 0
  image: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_builder_ipe: 0
  layout_builder_modal: 0
  layout_builder_operation_link: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_publishable_variants: 0
  page_manager_ui: 0
  path: 0
  path_alias: 0
  publishcontent: 0
  rabbit_hole: 0
  responsive_image: 0
  rh_taxonomy: 0
  settings_tray: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  system: 0
  taxonomy: 0
  text: 0
  tippy: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  pathauto: 1
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  common_design: 0
  common_design_subtheme: 0
  claro: 0
  gin: 0
profile: minimal
