definitions:
  'admin_toolbar_tools__extra_links:node__add__financials':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    expanded: false
    weight: 0
  'admin_toolbar_tools__extra_links:node__add__population':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:node__add__profile':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:node__add__risk_index':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:node__add__overview':
    enabled: true
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
  entity__base_object__collection:
    menu_name: admin
    parent: entity.base_object
    weight: 100
    expanded: false
    enabled: true
  entity__base_object_type__collection:
    weight: 101
    menu_name: admin
    parent: entity.base_object
    enabled: true
    expanded: false
  update__status:
    weight: 1
    menu_name: admin
    parent: system.admin_reports
    enabled: true
    expanded: false
  dblog__overview:
    weight: 2
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  locale__translate_status:
    weight: 3
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  entity__field_storage_config__collection:
    weight: 4
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  hpc_api__import_files_report:
    weight: 6
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  dblog__access_denied:
    weight: 7
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  dblog__page_not_found:
    weight: 8
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  views_ui__reports_plugins:
    weight: 5
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
