_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  'admin_toolbar_tools__extra_links:node__add__financials':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 4
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__population':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 7
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__profile':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 8
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__risk_index':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 9
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__overview':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 0
    expanded: false
    enabled: true
  entity__base_object__collection:
    menu_name: admin
    parent: entity.base_object
    weight: 100
    expanded: false
    enabled: true
  update__status:
    menu_name: admin
    parent: system.admin_reports
    weight: 1
    expanded: false
    enabled: true
  dblog__overview:
    menu_name: admin
    parent: system.admin_reports
    weight: 2
    expanded: false
    enabled: true
  locale__translate_status:
    menu_name: admin
    parent: system.admin_reports
    weight: 3
    expanded: false
    enabled: true
  entity__field_storage_config__collection:
    menu_name: admin
    parent: system.admin_reports
    weight: 4
    expanded: false
    enabled: true
  hpc_api__import_files_report:
    menu_name: admin
    parent: system.admin_reports
    weight: 6
    expanded: false
    enabled: true
  dblog__access_denied:
    menu_name: admin
    parent: system.admin_reports
    weight: 7
    expanded: false
    enabled: true
  dblog__page_not_found:
    menu_name: admin
    parent: system.admin_reports
    weight: 8
    expanded: false
    enabled: true
  views_ui__reports_plugins:
    menu_name: admin
    parent: system.admin_reports
    weight: 5
    expanded: false
    enabled: true
  system__admin_content:
    menu_name: admin
    parent: system.admin
    weight: -99
    expanded: false
    enabled: true
  system__admin_structure:
    menu_name: admin
    parent: system.admin
    weight: -98
    expanded: false
    enabled: true
  system__themes_page:
    menu_name: admin
    parent: system.admin
    weight: -97
    expanded: false
    enabled: true
  system__modules_list:
    menu_name: admin
    parent: system.admin
    weight: -96
    expanded: false
    enabled: true
  system__admin_config:
    menu_name: admin
    parent: system.admin
    weight: -95
    expanded: false
    enabled: true
  entity__user__collection:
    menu_name: admin
    parent: system.admin
    weight: -94
    expanded: false
    enabled: true
  system__admin_reports:
    menu_name: admin
    parent: system.admin
    weight: -93
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    menu_name: admin
    parent: system.admin_content
    weight: 4
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    menu_name: admin
    parent: system.admin_content
    weight: 5
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:user__admin_permissions':
    menu_name: admin
    parent: entity.user.collection
    weight: 2
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__user_role__collection':
    menu_name: admin
    parent: entity.user.collection
    weight: 3
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__article':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 2
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__document':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 3
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__news_story':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 5
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__page':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 6
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add__section':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:node.add'
    weight: 1
    expanded: false
    enabled: true
  entity__base_object_type__collection:
    menu_name: admin
    parent: system.admin_structure
    weight: 0
    expanded: false
    enabled: true
