_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  autologout: 0
  bert: 0
  big_pipe: 0
  big_pipe_sessionless: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cer: 0
  ckeditor5: 0
  config: 0
  config_default_image: 0
  config_default_responsive_image: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  editor: 0
  entity_access_password: 0
  entity_access_password_session_backend: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  fpa: 0
  ghi_base_objects: 0
  ghi_blocks: 0
  ghi_content: 0
  ghi_embargoed_access: 0
  ghi_form_elements: 0
  ghi_gin: 0
  ghi_hero_image: 0
  ghi_local_tasks: 0
  ghi_menu: 0
  ghi_plan_clusters: 0
  ghi_plans: 0
  ghi_search: 0
  ghi_sections: 0
  ghi_subpages: 0
  ghi_subpages_custom: 0
  ghi_teams: 0
  ghi_templates: 0
  ghi_user: 0
  gho_footnotes: 0
  gin_lb: 0
  gin_toolbar: 0
  google_tag: 0
  hpc_api: 0
  hpc_common: 0
  hpc_downloads: 0
  hpc_security: 0
  image: 0
  image_widget_crop: 0
  imageapi_optimize: 0
  imagecache_external: 0
  imagemagick: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_builder_ipe: 0
  layout_builder_lock: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  link: 0
  locale: 0
  maintenance200: 0
  media: 0
  media_library: 0
  memcache: 0
  menu_item_extras: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  ocha_snap: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_publishable_variants: 0
  page_manager_ui: 0
  path: 0
  path_alias: 0
  phpexcel: 0
  protected_pages: 0
  publishcontent: 0
  queue_ui: 0
  rabbit_hole: 0
  redirect: 0
  responsive_image: 0
  rh_taxonomy: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  seckit: 0
  settings_tray: 0
  smugmug_api: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  sophron: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  username_enumeration_prevention: 0
  view_unpublished: 0
  views_autocomplete_filters: 0
  viewsreference: 0
  warmer: 0
  warmer_cdn: 0
  webp: 0
  pathauto: 1
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  common_design: 0
  common_design_subtheme: 0
  claro: 0
  gin: 0
profile: minimal
