sync_source: 'https://hum-insight.info/'
access_key: ''
_core:
  default_config_hash: EUme9KS2VfxTESc5BX_gkXaKewmPiO8b-glUb5lg7UM
basic_auth:
  user: ''
  pass: ''
node_types:
  - section
  - population
