_core:
  default_config_hash: JC7xAOn1WxvHaeA3vpotjaW0X1GNsdGV0ITJ0sJfBCc
logo_path: ''
logo_path_xls: themes/custom/common_design_subtheme/img/logos/logo-humanitarian-action-xls.png
download_lifetime: null
excel_segment_size: null
excel_footnotes_as_data_validation_message: false
