_core:
  default_config_hash: UYGkeE2iH3UGp9lBPsELb3VSgHz9vkMJeaGzcYwE7Uw
settings:
  library_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js'
  css_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.css'
  crop_preview_image_style: crop_thumbnail
  crop_list:
    14x5: 14x5
    16x9: 16x9
  crop_types_required: {  }
  warn_multiple_usages: false
  show_default_crop: true
  show_crop_area: false
  notify_apply: false
  notify_update: false
