disable_layout_page: true
hide_local_tasks_block: false
show_discard_changes_link: true
enhance_ui: true
override_entity_changed_constraint: true
non_concurrent_editing: true
lock_layout: false
lock_message: ''
