_core:
  default_config_hash: CSLsGbxp3SlqyxyFdo_ySU0CldlmJux5IKpG9zYn4V0
ui_localtask: false
ui_checkbox: true
create_revision: false
create_log_entry: true
publish_text_value: Display
unpublish_text_value: "Don't display"
