_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
auth:
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/contrib/social_auth_google/img/google_logo.svg
post_login: /
user_allowed: register
redirect_user_form: false
disable_admin_login: true
disabled_roles:
  administrator: '0'
  global_editor: '0'
  editor: '0'
  rpm_administrator: '0'
  plan_lead: '0'
  cluster_lead: '0'
