_core:
  default_config_hash: wLhhL58IKPWkAbhxcI6gpCna7d431Q7kM0y-Om92BUQ
warmers:
  sitemap:
    id: sitemap
    frequency: 300
    batchSize: 50
    minPriority: !!float 0
    sitemaps: {  }
    headers: {  }
    verify: true
    maxConcurrentRequests: 10
  cdn:
    id: cdn
    frequency: 300
    batchSize: 3
    urls:
      - /
      - /overview/2022
      - /overview/2021
      - /overview/2020
      - /plan/1100
      - /plan/1061
      - /plan/1082
      - /plan/1087
      - /plan/1075
      - /plan/1080
      - /plan/1090
      - /plan/1092
      - /plan/1084
      - /plan/1079
      - /plan/1085
      - /plan/1096
      - /plan/1086
      - /plan/1083
      - /plan/1099
      - /plan/1060
      - /plan/1067
      - /plan/1104
      - /plan/1076
      - /plan/1106
      - /plan/1094
      - /plan/1095
      - /plan/1078
      - /plan/1062
      - /plan/1059
      - /plan/1108
      - /plan/1101
      - /plan/1069
      - /plan/1066
      - /plan/1064
      - /plan/1093
      - /plan/1063
      - /plan/1098
      - /plan/1071
      - /plan/1107
      - /plan/1068
      - /plan/1088
      - /plan/1072
      - /plan/1091
      - /plan/1102
      - /plan/1103
      - /plan/1097
      - /plan/1077
    headers: {  }
    verify: true
    maxConcurrentRequests: 5
