#!/bin/sh

# Lint PHP files
include='^html/(modules|themes)/custom/.*\.php$'
exclude=' '

# The linter path is relative to the root of the repository.
relative=1
linter="vendor/bin/phpcs"
options='-p --report=full --standard=phpcs.xml'
message='Linting staged PHP/CSS files...'

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
