ghi_blocks.map_settings:
  type: config_object
  label: 'GHI Map settings'
  mapping:
    mapbox_proxy:
      type: boolean
      label: 'Proxy requests to mapbox.com'
    country_outlines:
      type: boolean
      label: 'Show country outlines'