<?php

/**
 * @file
 * Contains hook implementations for the GHI Homepage module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\ghi_homepage\Entity\Homepage;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ghi_homepage_entity_bundle_info_alter(array &$bundles) {
  $bundles['node'][Homepage::BUNDLE]['class'] = Homepage::class;
  $bundles['node'][Homepage::BUNDLE]['label'] = t('Homepage');
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 *
 * This is used to add a constraint to the homepage node type to guarantee
 * unique years.
 */
function ghi_homepage_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if (($entity_type->id() === 'node') && ($bundle === Homepage::BUNDLE) && isset($fields['field_year'])) {
    $fields['field_year']->addConstraint('UniqueYear', []);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function ghi_homepage_preprocess_page(&$variables) {
  $node = $variables['node'] ?? NULL;
  if (!$node || !$node instanceof Homepage || \Drupal::routeMatch()->getRouteName() != 'entity.node.canonical') {
    return;
  }

  $message = [
    '#theme' => 'ghi_message',
    '#message' => t("This is the content container for the @year homepage. The content elements setup on this page are embeded automatically on the public homepage for @year and will be wrapped with common elements configured on the homepage. The page that you currently see will never be publicly available on it's own.", [
      '@year' => $node->getYear(),
    ]),
  ];

  $variables['page']['help'] = ['message' => $message];
}
