<?php

/**
 * @file
 * Contains hook implementations for the GHI Subpages module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\ghi_subpages\Controller\SubpagesAdminController;
use Drupal\ghi_subpages\Element\LayoutBuilderSectionLock;
use Drupal\ghi_subpages\Entity\LogframeSubpage;
use Drupal\ghi_subpages\Entity\SubpageNodeInterface;
use Drupal\ghi_subpages\Helpers\SubpageHelper;
use Drupal\ghi_subpages\SubpageManager;
use Drupal\hpc_common\Helpers\StringHelper;
use Drupal\layout_builder\SectionStorageInterface;
use Drupal\node\Form\NodeDeleteForm;
use Drupal\node\NodeInterface;
use Drupal\node\NodeTypeForm;
use Drupal\node\NodeTypeInterface;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ghi_subpages_entity_bundle_info_alter(array &$bundles) {
  foreach (SubpageManager::SUPPORTED_SUBPAGE_TYPES as $subpage_type) {
    $class_name = '\\Drupal\ghi_subpages\\Entity\\' . StringHelper::makeCamelCase($subpage_type, FALSE) . 'Subpage';
    if (!class_exists($class_name)) {
      continue;
    }
    $bundles['node'][$subpage_type]['class'] = $class_name;
    $bundles['node'][$subpage_type]['label'] = ucfirst(str_replace('_', ' ', $subpage_type));
  }
}

/**
 * Implements hook_section_post_save().
 *
 * Go over all created subpages for a node and save it again, to fix an issue
 * with the generation of url alias for subpages, if the pattern uses the
 * section's url alias as one of their tokens.
 */
function ghi_subpages_section_post_save(NodeInterface $section_node) {
  if (!SubpageHelper::isBaseTypeNode($section_node)) {
    return;
  }

  // Make sure all subpages exist.
  SubpageHelper::assureSubpagesForBaseNode($section_node);

  // Load all subpages and save them again to make sure they have proper paths.
  $subpages = SubpageHelper::loadSubpagesForBaseNode($section_node);
  foreach ($subpages as $subpage) {
    $subpage->setSyncing(TRUE);
    $subpage->save();
  }

  if (!$section_node->isPublished()) {
    // Load all subpages and make sure that those are unpublished too.
    $subpages = SubpageHelper::loadSubpagesForBaseNode($section_node);

    if (!empty($subpages)) {
      foreach ($subpages as $subpage) {
        if (!$subpage->isPublished()) {
          continue;
        }
        /** @var \Drupal\node\Entity\NodeInterface $node_type */
        $node_type = \Drupal::entityTypeManager()->getStorage('node_type')->load($subpage->getType());
        $subpage->setUnpublished();
        $subpage->save();

        \Drupal::messenger()->addStatus(t('Subpage @subpage has been unpublished.', [
          '@subpage' => $node_type->get('name'),
        ]));
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Invalidate cache tags for the section and all subpages if a new subpage is
 * created.
 */
function ghi_subpages_node_insert(NodeInterface $node) {
  if (!SubpageHelper::isSubpageTypeNode($node)) {
    // We act only on subpage nodes.
    return;
  }
  $cache_tags = $node->getCacheTags();
  $section_node = SubpageHelper::getBaseTypeNode($node);
  if (!$section_node) {
    return;
  }
  $subpages = SubpageHelper::loadSubpagesForBaseNode($section_node) ?? [];
  foreach ($subpages as $subpage) {
    $cache_tags = Cache::mergeTags($cache_tags, $subpage->getCacheTags());
  }
  Cache::invalidateTags($cache_tags);
}

/**
 * Implements hook_entity_delete().
 */
function ghi_subpages_entity_delete(EntityInterface $entity) {
  if (!$entity instanceof NodeInterface || !SubpageHelper::isBaseTypeNode($entity)) {
    return;
  }
  SubpageHelper::deleteSubpagesForBaseNode($entity);
}

/**
 * Implements hook_entity_access().
 *
 * Check access for full page node views of subpages of the base entities.
 * Allow access only if the base entity is allowed to be viewed.
 */
function ghi_subpages_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if (!$entity instanceof NodeInterface) {
    return AccessResult::neutral();
  }
  $node_types = SubpageManager::SUPPORTED_SUBPAGE_TYPES + [
    'plan_entity',
    'governing_entity',
  ];
  $node = $entity;
  if (!in_array($node->getType(), $node_types)) {
    // No opinion.
    return AccessResult::neutral();
  }

  if ($operation == 'view') {
    $base_entity = NULL;
    if ($node->hasField('field_entity_reference')) {
      /** @var \Drupal\node\NodeInterface $base_entity */
      $base_entity = $node->field_entity_reference->entity;
    }
    elseif ($node->hasField('field_plan')) {
      /** @var \Drupal\node\NodeInterface $base_entity */
      $base_entity = $node->field_plan->entity;
    }
    if (!$base_entity) {
      // No opinion.
      return AccessResult::neutral();
    }
    // If no access to the base entity, explicitely deny access to the subpage,
    // otherwhise follow whatever the node grants permit (neutral).
    $access_result = $base_entity->access($operation, $account) !== TRUE ? AccessResult::forbidden() : AccessResult::neutral();
    return $access_result->addCacheableDependency($entity);
  }

  // No opinion.
  return AccessResult::neutral();
}

/**
 * Implements hook_local_tasks_alter().
 *
 * This is used to remove the publish local task coming from the
 * publishcontent module, if it's configured to not display them. This is
 * needed because we alter the route requirements and remove a custom
 * access check which would normally govern the display of the task, in order
 * to be able to use the direct publish/unpublish link from other parts of the
 * site.
 */
function ghi_subpages_local_tasks_alter(&$local_tasks) {
  if (!empty($local_tasks['entity.node.publish'])) {
    $config = \Drupal::configFactory()->get('publishcontent.settings');
    if (empty($config->get('ui_localtask'))) {
      unset($local_tasks['entity.node.publish']);
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add a custom submit handler to the delete forms of subpage nodes, so that
 * users are redirected to the section overview page after deleting a subpage.
 *
 * @see ghi_subpages_node_subpage_delete_form_submit()
 */
function ghi_subpages_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof NodeDeleteForm) {
    $form['actions']['submit']['#submit'][] = 'ghi_subpages_node_subpage_delete_form_submit';
    return;
  }
  if ($form_object instanceof ContentEntityForm && $form_object->getEntity() instanceof SubpageNodeInterface) {
    $form['path']['widget']['#access'] = FALSE;
  }
}

/**
 * Custom submit handler for the delete forms of subpage nodes.
 *
 * Redirect to the section overview page after deleting a subpage.
 */
function ghi_subpages_node_subpage_delete_form_submit(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\node\Form\NodeDeleteForm $form_object */
  $form_object = $form_state->getFormObject();
  $entity = $form_object->getEntity();
  $section_node = SubpageHelper::getBaseTypeNode($entity);
  if ($section_node) {
    $form_state->setRedirectUrl($section_node->toUrl());
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ghi_subpages_form_node_type_edit_form_alter(array &$form, FormStateInterface $form_state) {
  $form_object = $form_state->getFormObject();
  if (!$form_object instanceof NodeTypeForm) {
    return;
  }
  /** @var \Drupal\node\Entity\NodeType $type */
  $type = $form_object->getEntity();
  if (!$type instanceof NodeTypeInterface || !SubpageHelper::isSubpageType($type)) {
    return;
  }
  $form['name']['#weight'] = -2;
  $form['page_title'] = [
    '#title' => t('Page title'),
    '#type' => 'textfield',
    '#default_value' => $type->getThirdPartySetting('ghi_subpages', 'page_title'),
    '#description' => t('A title that will be used as a page title on content of this type. Leave empty to use the name of the content type as set above.'),
    '#size' => 50,
    '#weight' => -1,
  ];
  array_unshift($form['actions']['submit']['#submit'], 'ghi_subpages_form_node_type_edit_form_submit');
}

/**
 * Submit handler for node type forms for subpage node types.
 */
function ghi_subpages_form_node_type_edit_form_submit(array $form, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeTypeForm $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\node\Entity\NodeType $type */
  $type = $form_object->getEntity();
  $type->setThirdPartySetting('ghi_subpages', 'page_title', $form_state->getValue('page_title'));
}

/**
 * Implements hook_entity_operation().
 */
function ghi_subpages_entity_operation(EntityInterface $entity) {
  $account = \Drupal::currentUser();
  if (!$entity instanceof NodeInterface || !SubpageHelper::isBaseTypeNode($entity)) {
    return;
  }

  $route_name = "ghi_subpages.node.pages";
  $route_parameters = [
    'node' => $entity->id(),
  ];

  // If current user has access to route, then add the operation link. The
  // access check will only return TRUE if the bundle is Layout Builder-
  // enabled, overrides are allowed, and user has necessary permissions.
  /** @var \Drupal\Core\Access\AccessManagerInterface $access_manager */
  $access_manager = \Drupal::service('access_manager');
  if (!$access_manager->checkNamedRoute($route_name, $route_parameters, $account)) {
    return;
  }

  return [
    'subpages' => [
      'title' => t('Subpages'),
      'weight' => 50,
      'url' => Url::fromRoute($route_name, $route_parameters),
    ],
  ];
}

/**
 * Implements hook_current_section_alter().
 */
function ghi_subpages_current_section_alter(&$section, $node) {
  if (!$node instanceof SubpageNodeInterface) {
    return NULL;
  }
  $section = $node->getParentNode();
}

/**
 * Implements hook_preprocess_page_title().
 */
function ghi_subpages_preprocess_page_title(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!$node instanceof NodeInterface || \Drupal::routeMatch()->getRouteName() != 'entity.node.canonical' || !empty($variables['#protected'])) {
    return;
  }
  if (SubpageHelper::isSubpageTypeNode($node) && $section = SubpageHelper::getBaseTypeNode($node)) {
    $variables['title'] = $section->getPageTitle();
  }
}

/**
 * Implements hook_preprocess_node_add_list().
 *
 * Filter the list of content types that are available for manual creation, so
 * that subpages can not be created individually.
 * Access is actually already denied via
 * Drupal\ghi_subpages\EventSubscriber\RouteSubscriber::alterRoutes, which
 * controls access on the node.add route. For the super admin, this doesn't
 * filter the list on the node add page itself though.
 */
function ghi_subpages_preprocess_node_add_list(&$variables) {
  if (!empty($variables['content'])) {
    $subpages_admin_controller = SubpagesAdminController::create(\Drupal::getContainer());
    foreach ($variables['content'] as $key => $type) {
      if ($subpages_admin_controller->nodeCreateAccess($type)->isForbidden()) {
        unset($variables['content'][$key]);
        unset($variables['types'][$type->id()]);
      }
    }
  }
}

/**
 * Implements hook_lement_info_alter().
 */
function ghi_subpages_element_info_alter(array &$types) {
  $types['layout_builder']['#pre_render'][] = [
    LayoutBuilderSectionLock::class,
    'preRenderRestrictSectionConfiguration',
  ];
}

/**
 * Implements hook_layout_builder_ipe_links_alter().
 *
 * This adds additional links to the IPE action section.
 */
function ghi_subpages_layout_builder_ipe_links_alter(array &$links, SectionStorageInterface $section_storage, EntityInterface $entity) {
  if (!$entity instanceof LogframeSubpage) {
    // We only support this for content entites.
    return;
  }
  /** @var \Drupal\ghi_subpages\LayoutBuilder\LogframeRebuildLinkBuilder $link_builder */
  $link_builder = \Drupal::service('ghi_subpages.link_builder');
  $rebuild_link = $link_builder->buildLogframeRebuildLink($section_storage, $entity);
  if ($rebuild_link && $rebuild_link->getUrl()->access()) {
    $links['logframe'] = $rebuild_link->toRenderable();
  }
}

/**
 * Returns true if the current route is a layout builder route.
 *
 * @return bool
 *   Returns true for layout builder routes.
 */
function ghi_subpages_is_layout_builder_route() {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if (!$route_name) {
    return FALSE;
  }
  return $route_name == 'ghi_subpages.entity.logframe_rebuild';
}

/**
 * Implements hook_gin_lb_is_layout_builder_route_alter().
 *
 * Define a the export/import forms to be a layout builder route.
 */
function ghi_subpages_gin_lb_is_layout_builder_route_alter(&$gin_lb_is_layout_builder_route, $context) {
  if (ghi_subpages_is_layout_builder_route()) {
    $gin_lb_is_layout_builder_route = ghi_subpages_is_layout_builder_route();
  }
}
