#!/usr/bin/env bash
#: exec_target = cli

## Run the code quality checks
##
## Usage: fin cs

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

# Abort if anything fails
set -e

usage="$(basename "$0") [-h] [-i]

where:
    -h  show this help text"

echo "Running code linting on PHP code"
./vendor/bin/phpcs -p --report=full ./html/modules/custom --extensions=module/php,php/php,inc/php

echo "Checking for Drupal standards"
./vendor/bin/phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml ./html/modules/custom/