ghi_embargoed_access.settings:
  type: config_object
  translatable: true
  label: 'Settings'
  mapping:
    enabled:
      type: 'boolean'
      label: 'Whether the embargoed access is enabled or not'

action.configuration.protect_content:
  type: action_configuration_default
  label: 'Protect the selected content configuration'

action.configuration.unprotect_content:
  type: action_configuration_default
  label: 'Unprotect the selected content configuration'