ghi_embargoed_access.settings:
  type: config_object
  translatable: true
  label: 'Settings'
  mapping:
    enabled:
      type: 'boolean'
      label: 'Whether the embargoed access is enabled or not'