name: CI

on:
  pull_request:
    branches:
      - dev
      - main
      - release-versions/v**

jobs:
  Code_Quality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Composerify
      run: composer install
    - name: Check code syntax with php.
      run: |
        test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
        test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
    - name: Check code quality with phpcs.
      run: |
        test ! -d ./html/modules/custom || ./vendor/bin/phpcs -p --report=full ./html/modules/custom --extensions=module/php,php/php,inc/php
        test ! -d ./html/themes/custom || ./vendor/bin/phpcs -p --report=full ./html/themes/custom
    # - name: Check code complexity with phpmd.
    #   run: |
    #     test ! -d ./html/modules/custom || ./vendor/bin/phpmd ./html/modules/custom text .phpmd.xml --suffixes=php,inc,module,install
    #     test ! -d ./html/themes/custom || ./vendor/bin/phpmd ./html/themes/custom text .phpmd.xml --suffixes=php,inc,module,install
    # - name: Check code duplication with phpcpd.
    #   run: |
    #     test ! -d ./html/modules/custom || ./vendor/bin/phpcpd ./html/modules/custom --names=*.php,*.inc,*.module,*.install --names-exclude=*.features.*,*.panelizer.inc,*.views_default.inc,*.pages_default.inc,*.field_group.inc,*.strongarm.inc,*.facetapi_defaults.inc,*.ds.inc,*..inc,*.default_environment_indicator_environments.inc
    #     test ! -d ./html/themes/custom || ./vendor/bin/phpcpd ./html/themes/custom --names=*.php,*.inc,*.module,*.install
